In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5 7 9]
print(a * b)   # [ 4 10 18]


In [ ]:
a = np.array([1, 2, 3])

print(a + 5)   # [6 7 8]
print(a * 2)   # [2 4 6]


In [ ]:
a = np.array([[1], [2], [3]])  # shape (3,1)
b = np.array([10, 20, 30])     # shape (3,)

# a is broadcast across columns, b across rows
print(a + b)
# [[11 21 31]
#  [12 22 32]
#  [13 23 33]]

In [ ]:
a = np.array([[1, 2, 3]])   # shape (1,3)
b = np.array([[10], [20]])  # shape (2,1)

print(a + b)
# [[11 12 13]
#  [21 22 23]]

In [ ]:
a = np.array([1, 2, 3])          # shape (3,)
b = np.array([[10], [20], [30]]) # shape (3,1)

# Expand a → shape (1,3), then match b → shape (3,3)
print(a + b)
# [[11 12 13]
#  [21 22 23]
#  [31 32 33]]