# NumPy Array Slicing — Guide & Exercises

*Generated on 2025-09-11*

This notebook covers NumPy slicing essentials with runnable examples, followed by exercises where you **predict the result/shape** and then **reveal** the answers.

In [2]:
import numpy as np
np.set_printoptions(edgeitems=20, linewidth=120, suppress=True)


## 1) The Basics: `start:stop:step`
- Half-open intervals: `start` inclusive, `stop` exclusive
- Any part may be omitted: defaults are `start=0`, `stop=len`, `step=1`
- Negative indices count from the end; negative `step` reverses
- Slices return **views** (no copy) when possible

In [5]:
a = np.arange(10)        # [0 1 2 3 4 5 6 7 8 9]
print("a:", a)
print("a[2:7]     ->", a[2:7])
print("a[:5]      ->", a[:5])
print("a[5:]      ->", a[5:])
print("a[::2]     ->", a[::2])
print("a[::-1]    ->", a[::-1])
print("a[-4:-1]   ->", a[-4:-1])

a: [0 1 2 3 4 5 6 7 8 9]
a[2:7]     -> [2 3 4 5 6]
a[:5]      -> [0 1 2 3 4]
a[5:]      -> [5 6 7 8 9]
a[::2]     -> [0 2 4 6 8]
a[::-1]    -> [9 8 7 6 5 4 3 2 1 0]
a[-4:-1]   -> [6 7 8]


## 2) 2D Slicing: `rows, cols`
Use a comma to slice each axis independently.

In [6]:
M = np.arange(1, 13).reshape(3, 4)
print("M:\n", M)
print("M[0, :]      ->", M[0, :])        # first row
print("M[:, 0]      ->", M[:, 0])        # first column
print("M[:2, :3]    ->\n", M[:2, :3])    # top-left 2x3 block
print("M[::2, ::2]  ->\n", M[::2, ::2])  # every other row/col

M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
M[0, :]      -> [1 2 3 4]
M[:, 0]      -> [1 5 9]
M[:2, :3]    ->
 [[1 2 3]
 [5 6 7]]
M[::2, ::2]  ->
 [[ 1  3]
 [ 9 11]]


## 3) 3D Slicing and Ellipsis `...`
Ellipsis fills in remaining axes automatically.

In [35]:
X = np.arange(2*3*4).reshape(2, 3, 4)  # shape (2,3,4)
print("X shape:", X.shape)
print("X[0, :, :].shape ->", X[0, :, :].shape)
print("X[:, 1, :].shape ->", X[:, 1, :].shape)
print("X[..., 0].shape  ->", X[..., 0].shape)
print("X[1, ..., ::2].shape ->", X[1, ..., ::2].shape)

X shape: (2, 3, 4)
X[0, :, :].shape -> (3, 4)
X[:, 1, :].shape -> (2, 4)
X[..., 0].shape  -> (2, 3)
X[1, ..., ::2].shape -> (3, 2)


## 4) Assigning to Slices (in-place edits)
Slicing returns views, so writes modify the original.

In [4]:
A = np.zeros((4, 5), dtype=int)
A[1:3, 2:5] = 7         # fill a submatrix
print("A after fill:\n", A)
A[:, 0] = np.arange(4)  # set first column
print("A after setting col0:\n", A)

A after fill:
 [[0 0 0 0 0]
 [0 0 7 7 7]
 [0 0 7 7 7]
 [0 0 0 0 0]]
A after setting col0:
 [[0 0 0 0 0]
 [1 0 7 7 7]
 [2 0 7 7 7]
 [3 0 0 0 0]]


## 5) Views vs Copies
- **Slicing** → view (shared memory)
- **Fancy/boolean indexing** → copy

In [18]:
B = np.arange(10)
s = B[2:8:2]        # slice -> view
s[:] = -1
print("B changed via slice view:", B)

C = np.arange(10)
f = C[[2,4,6]]      # fancy -> copy
f[:] = -1
print("C unchanged after fancy copy:", C)

B changed via slice view: [ 0  1 -1  3 -1  5 -1  7  8  9]
C unchanged after fancy copy: [0 1 2 3 4 5 6 7 8 9]


## 6) Using `None` / `np.newaxis` to Add Axes
Insert a size-1 dimension to prepare for broadcasting.

In [20]:
v = np.arange(4)                 # (4,)
v_col = v[:, None]               # (4,1)
v_row = v[None, :]               # (1,4)
print("v_col : \n", v_col)
print("v_row : \n", v_row)
print("v_col shape:", v_col.shape, "v_row shape:", v_row.shape)
print("outer sum grid:\n", v_col + v_row)

v_col : 
 [[0]
 [1]
 [2]
 [3]]
v_row : 
 [[0 1 2 3]]
v_col shape: (4, 1) v_row shape: (1, 4)
outer sum grid:
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


## 7) Mixed Slicing & Boolean Masks (advanced)

In [21]:
Z = np.arange(1, 13).reshape(3, 4)
mask = Z[1] > 6          # apply predicate to row 1 over columns
print("Z:\n", Z)
print("mask (row1 > 6):", mask)
print("Z[1, mask] ->", Z[1, mask])
print("Z[:, mask] ->\n", Z[:, mask])

Z:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
mask (row1 > 6): [False False  True  True]
Z[1, mask] -> [7 8]
Z[:, mask] ->
 [[ 3  4]
 [ 7  8]
 [11 12]]


---
# Exercises: Predict, Then Reveal
For each exercise:
1. **Predict** the result and/or shape in your head (or write it down).
2. Run the **Reveal** cell to check your answer.

> Tip: many of these rely on half-open intervals and view semantics.


### Exercise 1 — 1D Slices
Predict the outputs for:
- `a[1:6:2]`
- `a[-5:-1]`
- `a[::-2]`

In [22]:
# Setup
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Reveal
print("a[1:6:2] ->", a[1:6:2]) # 1 3 5
print("a[-5:-1] ->", a[-5:-1]) # 5 6 7 8
print("a[::-2]   ->", a[::-2]) # 9 7 5 3 1

a[1:6:2] -> [1 3 5]
a[-5:-1] -> [5 6 7 8]
a[::-2]   -> [9 7 5 3 1]


### Exercise 2 — 2D Crops & Strides
Given `M = np.arange(1, 17).reshape(4,4)`, predict:
- `M[1:3, 1:4]`
- `M[::2, ::-2]`
- `M[-2:, :2]`

In [24]:
M = np.arange(1, 17).reshape(4,4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
# Reveal
print("M[1:3, 1:4]:\n", M[1:3, 1:4]) # [[6 7 8] [10 11 12]]
print("M[::2, ::-2]:\n", M[::2, ::-2]) # [[4 2] [12 10]]
print("M[-2:, :2]:\n", M[-2:, :2]) # [[9 10] [13 14]]

M[1:3, 1:4]:
 [[ 6  7  8]
 [10 11 12]]
M[::2, ::-2]:
 [[ 4  2]
 [12 10]]
M[-2:, :2]:
 [[ 9 10]
 [13 14]]


### Exercise 3 — 3D Ellipsis
Let `X = np.arange(2*3*4).reshape(2,3,4)`. Predict the **shapes** of:
- `X[..., 0]`
- `X[1, ..., ::2]`
- `X[:, 1, :]`

In [26]:
X = np.arange(2*3*4).reshape(2,3,4)
X.shape

(2, 3, 4)

In [36]:
# Reveal shapes only
print("X[..., 0].shape   ->", X[..., 0].shape) # (2, 3)
print("X[1, ..., ::2].shape ->", X[1, ..., ::2].shape) # (3, 2)
print("X[:, 1, :].shape  ->", X[:, 1, :].shape) # (2, 4)

X[..., 0].shape   -> (2, 3)
X[1, ..., ::2].shape -> (3, 2)
X[:, 1, :].shape  -> (2, 4)


### Exercise 4 — Views vs Copies
Predict what happens to `B` in each case.

In [37]:
B = np.arange(12)
view = B[3:9]
view[:] = -1
copy = B[[1,3,5]]
copy[:] = 99
B

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10, 11])

In [38]:
# Reveal
print("B after modifying view and copy ->", B) # [0 1 2 -1 -1 -1 -1 -1 -1 9 10 11]
print("(Expect slice-view edits visible; fancy-index copy edits not)") # 

B after modifying view and copy -> [ 0  1  2 -1 -1 -1 -1 -1 -1  9 10 11]
(Expect slice-view edits visible; fancy-index copy edits not)


### Exercise 5 — Assigning to Slices
Fill a `5x6` zero matrix in the rectangle rows `1..3` and cols `2..5` with `7`. Predict the final array.

In [39]:
A = np.zeros((5,6), dtype=int)
A[1:4, 2:6] = 7
A

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 7, 7, 7, 7],
       [0, 0, 7, 7, 7, 7],
       [0, 0, 7, 7, 7, 7],
       [0, 0, 0, 0, 0, 0]])

### Exercise 6 — Row/Column Selection
Given `M = np.arange(1, 13).reshape(3,4)`, predict:
- `M[:, 0]`
- `M[0, :]`
- `M[:, ::2]`

In [40]:
M = np.arange(1, 13).reshape(3,4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
# Reveal
print("M[:, 0]  ->", M[:, 0]) # [1 5 9]
print("M[0, :]  ->", M[0, :]) # [1 2 3 4]
print("M[:, ::2]->\n", M[:, ::2]) # [[1 3] [5 7] [9 11]]

M[:, 0]  -> [1 5 9]
M[0, :]  -> [1 2 3 4]
M[:, ::2]->
 [[ 1  3]
 [ 5  7]
 [ 9 11]]


### Exercise 7 — Reversals
For `a = np.arange(8)`, predict:
- `a[::-1]`
- `a[1::-1]`
- `a[:-3:-1]`

In [3]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
# Reveal
print("a[::-1]   ->", a[::-1]) # [7 6 5 4 3 2 1 0]
print("a[1::-1]  ->", a[1::-1]) # [1 0]
print("a[:-3:-1] ->", a[:-3:-1]) # [7 6]

a[::-1]   -> [7 6 5 4 3 2 1 0]
a[1::-1]  -> [1 0]
a[:-3:-1] -> [7 6]


### Exercise 8 — Insert Axes
Let `v = np.arange(3)`. Predict the shapes of:
- `v[:, None]`
- `v[None, :]`
- `(v[:, None] + v[None, :])`

In [ ]:
v = np.arange(3)
v

In [ ]:
# Reveal
print("v[:, None].shape  ->", v[:, None].shape)
print("v[None, :].shape  ->", v[None, :].shape)
print("(v[:, None] + v[None, :]).shape ->", (v[:, None] + v[None, :]).shape)

### Exercise 9 — Mixed Slicing & Masking
Given `Z = np.arange(1, 13).reshape(3,4)` and `mask = Z[1] > 6`, predict:
- `Z[1, mask]`
- `Z[:, mask]` shape

In [ ]:
Z = np.arange(1, 13).reshape(3,4)
mask = Z[1] > 6
Z, mask

In [ ]:
# Reveal
print("Z[1, mask] ->", Z[1, mask])
print("Z[:, mask].shape ->", Z[:, mask].shape)

### Exercise 10 — Slicing with Steps in 2D
`M = np.arange(1, 26).reshape(5,5)`. Predict:
- `M[::2, 1::2]`
- `M[1::2, ::-2]`
- `M[::-2, ::2]`

In [ ]:
M = np.arange(1, 26).reshape(5,5)
M

In [ ]:
# Reveal
print("M[::2, 1::2]:\n", M[::2, 1::2])
print("M[1::2, ::-2]:\n", M[1::2, ::-2])
print("M[::-2, ::2]:\n", M[::-2, ::2])